/**
 * Accounting Helpers
 * Pure helper functies voor accounting module
 */

import type {
  Quote,
  Invoice,
  QuoteStatus,
  InvoiceStatus,
  WorkOrder,
  Customer,
  User,
  InventoryItem,
} from '../../../types';

// ============================================================================
// ENTITY NAME HELPERS
// ============================================================================

/**
 * Haal employee naam op aan de hand van ID
 */
export const getEmployeeName = (id: string, employees: User[]): string => {
  const employee = employees.find(e => e.id === id);
  return employee?.name || 'Onbekend';
};

/**
 * Haal customer naam op aan de hand van ID
 */
export const getCustomerName = (id: string, customers: Customer[]): string => {
  const customer = customers.find(c => c.id === id);
  return customer?.name || 'Onbekende klant';
};

/**
 * Haal inventory item naam op aan de hand van ID
 */
export const getInventoryItemName = (id: string, inventory: InventoryItem[]): string => {
  const item = inventory.find(i => i.id === id);
  return item?.name || 'Onbekend item';
};

// ============================================================================
// STATUS COLOR HELPERS
// ============================================================================

/**
 * Haal color class voor quote status
 */
export const getQuoteStatusColor = (status: QuoteStatus): string => {
  const colorMap: Record<QuoteStatus, string> = {
    draft: 'gray',
    sent: 'blue',
    approved: 'green',
    rejected: 'red',
    expired: 'orange',
  };
  return colorMap[status] || 'gray';
};

/**
 * Haal color class voor invoice status
 */
export const getInvoiceStatusColor = (status: InvoiceStatus): string => {
  const colorMap: Record<InvoiceStatus, string> = {
    draft: 'gray',
    sent: 'blue',
    paid: 'green',
    overdue: 'red',
    cancelled: 'gray',
  };
  return colorMap[status] || 'gray';
};

// ============================================================================
// WORKORDER HELPERS
// ============================================================================

/**
 * Haal workorder status op voor een quote/invoice
 */
export const getWorkOrderStatus = (workOrder?: WorkOrder): string => {
  if (!workOrder) return 'Geen werkorder';

  const statusMap = {
    todo: 'Te doen',
    pending: 'In afwachting',
    in_progress: 'In uitvoering',
    completed: 'Afgerond',
  };

  return statusMap[workOrder.status] || workOrder.status;
};

/**
 * Haal workorder badge element
 */
export const getWorkOrderBadge = (status: string): { text: string; color: string } => {
  const badgeMap: Record<string, { text: string; color: string }> = {
    todo: { text: 'Te doen', color: 'gray' },
    pending: { text: 'In afwachting', color: 'yellow' },
    in_progress: { text: 'In uitvoering', color: 'blue' },
    completed: { text: 'Afgerond', color: 'green' },
  };

  return badgeMap[status] || { text: status, color: 'gray' };
};

/**
 * Check of invoice auto-generated is vanuit werkorder
 */
export const isAutoGeneratedInvoice = (invoice: Invoice): boolean => {
  return !!invoice.workOrderId;
};

/**
 * Zoek werkorder voor een invoice
 */
export const getWorkOrderForInvoice = (
  invoiceId: string,
  workOrders: WorkOrder[]
): WorkOrder | undefined => {
  return workOrders.find(wo => wo.invoiceId === invoiceId);
};

/**
 * Zoek werkorder voor een quote
 */
export const getWorkOrderForQuote = (
  quoteId: string,
  workOrders: WorkOrder[]
): WorkOrder | undefined => {
  return workOrders.find(wo => wo.quoteId === quoteId);
};

// ============================================================================
// HISTORY HELPERS
// ============================================================================

/**
 * Maak een history entry voor logging
 */
export const createHistoryEntry = (
  action: string,
  entity: 'quote' | 'invoice' | 'transaction',
  entityId: string,
  userId: string,
  details?: Record<string, any>
): {
  id: string;
  action: string;
  entity: string;
  entityId: string;
  userId: string;
  timestamp: string;
  details?: Record<string, any>;
} => {
  return {
    id: `history-${Date.now()}`,
    action,
    entity,
    entityId,
    userId,
    timestamp: new Date().toISOString(),
    details,
  };
};

// ============================================================================
// RELATION HELPERS
// ============================================================================

/**
 * Check of quote linked is aan een werkorder
 */
export const isQuoteLinkedToWorkOrder = (quote: Quote): boolean => {
  return !!quote.workOrderId;
};

/**
 * Check of quote linked is aan een invoice
 */
export const isQuoteLinkedToInvoice = (quote: Quote): boolean => {
  return !!quote.invoiceId;
};

/**
 * Check of invoice linked is aan een werkorder
 */
export const isInvoiceLinkedToWorkOrder = (invoice: Invoice): boolean => {
  return !!invoice.workOrderId;
};

/**
 * Check of invoice linked is aan een quote
 */
export const isInvoiceLinkedToQuote = (invoice: Invoice): boolean => {
  return !!invoice.quoteId;
};

// ============================================================================
// DATE HELPERS
// ============================================================================

/**
 * Check of invoice overdue is
 */
export const isInvoiceOverdue = (invoice: Invoice): boolean => {
  if (invoice.status === 'paid' || invoice.status === 'cancelled') {
    return false;
  }

  const today = new Date();
  const dueDate = new Date(invoice.dueDate);

  return dueDate < today;
};

/**
 * Check of quote expired is
 */
export const isQuoteExpired = (quote: Quote): boolean => {
  if (!quote.validUntil) return false;

  const today = new Date();
  const validUntil = new Date(quote.validUntil);

  return validUntil < today;
};

/**
 * Bereken dagen tot betaling
 */
export const getDaysUntilDue = (invoice: Invoice): number => {
  const today = new Date();
  const dueDate = new Date(invoice.dueDate);

  const diffTime = dueDate.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  return diffDays;
};

/**
 * Bereken dagen overdue
 */
export const getDaysOverdue = (invoice: Invoice): number => {
  if (!isInvoiceOverdue(invoice)) return 0;

  return Math.abs(getDaysUntilDue(invoice));
};
